---
title: "Untitled"
author: "Dr. Amita Baranwal"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=TRUE}
library(readxl)
library(corrplot)

# importing excel file from local folder
data=read_excel("D:/LPU/Chapter/machine failure.xlsx")

head(data)
names(data)
dim(data)

data=data[,4:7]


#Pearson correlation between 2 variables 
cor(data$`Air temperature [K]`, data$`Rotational speed [rpm]`)

```



```{r }
# correlation for all variables 
round(cor(data), digits = 2) # rounded to 2 decimals 

#Scatterplots for several pairs of variables
corrplot(cor(data), method = "number", type = "upper") # show only upper side 

```


```{r }
library(ggplot2)

ggplot(data) +
  aes(x = `Air temperature [K]`, y = `Rotational speed [rpm]`) +
  geom_point(colour = "#0c4c8a") +
  theme_minimal()         

plot(data$`Air temperature [K]`, data$`Rotational speed [rpm]`)

# multiple scatterplots
pairs(data[, 1:4])
corrplot(cor(data),method = "number",type = "upper" )# show only upper side

```

